core/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, FormView

from core.views import KISPPageView
from core.models import Feedback

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from django.views.generic import DetailView

urlpatterns = patterns('',
    url(r'^$', 'core.views.index',name='index'),
    url(r'^about/$', KISPPageView.as_view(), {'viewname':'about'}, name="about"),
    url(r'^aboutoz/$', KISPPageView.as_view(), {'viewname':'aboutoz'}, name="aboutoz"),
    url(r'^request/$', KISPPageView.as_view(), {'viewname':'request'}, name="request"),
    url(r'^team/$', KISPPageView.as_view(), {'viewname':'team_table'}, name="team"),

    url(r'^event/$', 'core.views.event_list', name='event_list'),
    url(r'^event/(?P<eid>\d+)/$', 'core.views.event', name='event'),

    url(r'^event/(?P<eid>\d+)/export/$', 'core.xlexport.agent', name='export_agent'),
    url(r'^event/(?P<eid>\d+)/feedback/write/$', 'core.views.feedback_write', name='feedback_write'),
    url(r'^event/(?P<eid>\d+)/feedback/$', 'core.views.feedback', name='feedback'),
    url(r'^event/(?P<eid>\d+)/sms/$', 'core.views.send_sms_by_event'),

    url(r'^feedback/(?P<pk>\d+)/$', DetailView.as_view(model=Feedback)),
    url(r'^feedback/confirm/$', 'core.views.feedback_confirm', name='feedback_confirm'),
    url(r'^feedback/delete/$', 'core.views.feedback_delete', name='feedback_delete'),
    url(r'^feedback/update/$', 'core.views.feedback_update', name='feedback_update'),

    url(r'^event/image/add/(?P<eid>\d+)/$', 'core.views.event_image_add', name='event_image_add'),
    url(r'^event/image/del/(?P<eid>\d+)/(?P<iid>\d+)/$', 'core.views.event_image_del', name='event_image_del'),

    url(r'^entry/(?P<event_id>\d+)/preadd/$', 'core.views.entry_preadd', name='entry_preadd'),
    url(r'^entry/(?P<event_id>\d+)/add/$', 'core.views.entry_edit', name='entry_add'),
    url(r'^entry/(?P<event_id>\d+)/add/(?P<club>.+)/$', 'core.views.entry_edit', name='entry_add'),

    url(r'^entry/(?P<entry_id>\d+)/$', 'core.views.entry_view', name='entry_view'),
    url(r'^entry/(?P<entry_id>\d+)/edit/$', 'core.views.entry_edit', name='entry_edit'),

    url(r'^entry/(?P<event_id>\d+)/agent/add/$', 'core.views.agent_entry_edit', name='agent_entry_add'),
    url(r'^entry/(?P<event_id>\d+)/agent/edit/$', 'core.views.agent_entry_edit', name='agent_entry_edit'),
    url(r'^entry/(?P<event_id>\d+)/agent/del/$', 'core.views.agent_entry_del', name='agent_entry_del'),

    url(r'^contact/$', 'core.views.contact', name='contact'),

    url(r'^sms/entry/$', 'core.views.send_sms_by_entry', name='send_sms_by_entry'),
    url(r'^sms/event/(?P<eid>\d+)/$', 'core.views.send_sms_by_event', name='send_sms_by_event'),

    url(r'^sms/group/$', 'core.views.groups', name='group_select'),
    url(r'^sms/group/(?P<gid>\d+)/$', 'core.views.send_sms_by_group', name='send_sms_by_group'),


    url(r'^sms/reserve/entry/$', 'core.views.reserve_sms_by_entry', name='reserve_sms_by_entry'),
    url(r'^sms/reserve/event/(?P<eid>\d+)/$', 'core.views.reserve_sms_by_event', name='reserve_sms_by_event'),

    url(r'^sms/reserve/group/$', 'core.views.groups', name='group_select'),
    url(r'^sms/reserve/group/(?P<gid>\d+)/$', 'core.views.reserve_sms_by_group', name='reserve_sms_by_group'),

    url(r'^sms/reserve/worker/$', "core.views.reserved_sms_worker", name="reserved_sms_worker"),


    url(r'^signin/$', 'core.views.signin', name='signin'),
    url(r'^signout/$', 'core.views.signout', name='signout'),
    url(r'^signup/$', 'core.views.signup', name='signup'),
    url(r'^agent/$', 'core.views.agent_view', name='agent_view'),
    url(r'^agent/edit/$', 'core.views.agent_edit', name='agent_edit'),
    url(r'^passwd/$', 'core.views.change_pw', name='change_pw'),
    url(r'^reset/$', 'core.views.reset_pw', name='reset_pw'),

    url(r'^agent/image/(?P<agent_id>\d+)/$', 'core.views.agent_image', name='agent_image'),

    url(r'^timezone/$','core.timezone.test'),
    url(r'^temp_sms/$','core.views.temp_sms'),
    url(r'^temp_sms2/$','core.views.temp_sms2'),
)

kispapp/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the next line to enable the admin:
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('core.urls')),
) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

try:
    from django.conf.urls import url, patterns
except:
    from django.conf.urls.defaults import url, patterns

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

core/models.py
#!/usr/bin/env
# -*- coding:utf-8 -*-

from django.db import models
from djangotoolbox.fields import ListField, EmbeddedModelField
from core.fields import ModelListField
from tinymce.models import HTMLField

from django.template.defaultfilters import truncatechars  # or truncatewords
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from datetime import date, datetime, timedelta
from core import timezone

from gettext import gettext as _

import logging
logger = logging.getLogger('model')
logger.setLevel(logging.INFO)

class Series(models.Model):

	class Meta:
		verbose_name = u"시리즈 행사"
		verbose_name_plural = u"시리즈 행사 목록"

	def __unicode__(self):
		return self.title

	title = models.CharField(u'행사 시리즈 명',max_length=255)
	host = models.CharField(u'주최사', max_length=255)
	contact = models.TextField(u'연락처', blank=True)


class EventCompany(models.Model):

	class Meta:
		verbose_name = u"이벤트 업체"
		verbose_name_plural = u"이벤트 업체들"

	def __unicode__(self):
		return self.name

	name = models.CharField(u'업체명', max_length=255)
	desc = models.TextField(u'설명', blank=True)
	contact = models.TextField(u'연락처', blank=True)


class Course(models.Model):

	class Meta:
		verbose_name = u"# 코스 종류"
		verbose_name_plural = u"# 코스 종류 들"
		ordering = ['distance',]

	def __unicode__(self):
		return "%s (%s)"%(self.title,self.distance)

	title = models.CharField(u'코스명', max_length=255)
	distance = models.FloatField(u'거리')

EVENT_STATUS_INFO = {
	'ended':{
	'title':u'대회 종료',
	'description':u'모든 진행이 종료 되었습니다.',
	'class':'default'
	},
	'feedback':{
	'title':u'종료 보고 중',
	'description':u'대회가 종료 되었습니다. 종료 보고를 입력해주세요.',
	'class':'info'
	},
	'progress':{
	'title':u'대회 진행 중',
	'description':u'대회가 지금 현재 진행 중 입니다.',
	'class':'primary'
	},
	'organizing':{
	'title':u'모집 마감',
	'description':u'모집이 마감되었습니다.',
	'class':'danger'
	},
	'recruit_ending':{
	'title':u'모집 중',
	'description':u'곧 모집이 마감됩니다.',
	'class':'warning'
	},
	'recruit':{
	'title':u'모집 중',
	'description':u'모집을 진행중입니다.',
	'class':'success'
	},
	'ready_ending':{
	'title':u'모집 준비 중',
	'description':u'곧 모집을 시작합니다.',
	'class':'info'
	},
	'ready':{
	'title':u'모집 준비 중',
	'description':u'아직 모집 기간이 아닙니다.',
	'class':'default'
	},
	'none':{
	'title':u'',
	'description':u'',
	'class':'muted'
	}
}

class Event(models.Model):

	class Meta:
		verbose_name = u"행사"
		verbose_name_plural = u"행사들"
		ordering = ['-event_day']

	def __unicode__(self):
		return self.title

	def year_title(self):
		return '<code>'+self.event_day.strftime(u'%Y') + '</code> ' + self.short_title

	def course_list(self):
		return ", ".join( (course.title for course in Course.objects.filter(pk__in=self.course) ) )

	def entry_count(self):
		return Entry.objects.filter(event=self).count()

	def is_registable(self):

		today = timezone.today()

		if self.recruit_open > today:
			return False
		if self.recruit_deadline < today:
			return False

		return True

	def can_feedback(self):
		status = self.get_status()
		return status in ('progress','feedback','ended')

	def location_tag(self):
		if self.location_url:
			return '<a href="%s">%s</a>'%(self.location_url, self.location)

		return self.location

	def event_day_display(self):
		WEEKDAY_KOR = u"월화수목금토일-------"
		return u"%s년 %s월 %s일 (%s)"%(self.event_day.year, self.event_day.month, self.event_day.day, WEEKDAY_KOR[self.event_day.weekday()])

	def featured_image(self):
		try:
			return EventImage.objects.get(event=self, featured=True).image.url+'=s280-c'
		except:
			pass

		try:
			return EventImage.objects.filter(event=self, featured=False)[0].image.url+'=s280-c'
		except:
			pass

		return 'http://placehold.it/280x280&text=no+image'

	def get_status(self):

		today = timezone.today()
		tomorrow = today + timedelta(days=1)

		status = 'none';

		if self.feedback_deadline < today:
			status = 'ended'

		elif self.event_day < today and self.feedback_deadline >= today:
			status = 'feedback'

		elif self.event_day == today:
			status = 'progress'

		elif self.recruit_deadline < today:
			status = 'organizing'

		elif self.recruit_open <= today:
			status = 'recruit'

		elif self.recruit_open > today:
			status = 'ready'

		return status

	def get_status_info(self):

		today = timezone.today()

		tomorrow = today + timedelta(days=1)

		status = 'none';

		if self.feedback_deadline < today:
			status = 'ended'

		elif self.event_day < today and self.feedback_deadline >= today:
			status = 'feedback'

		elif self.event_day == today:
			status = 'progress'

		elif self.recruit_deadline < today:
			status = 'organizing'

		elif self.recruit_open <= today:
			if self.recruit_deadline == tomorrow:
				status = 'recruit_ending'

			elif self.recruit_deadline >= today:
				status = 'recruit'

		elif self.recruit_open == tomorrow:
			status = 'ready_ending'

		elif self.recruit_open > today:
			status = 'ready'

		return EVENT_STATUS_INFO[status]

	def get_status_text(self):
		return self.get_status_info()['title']

	def get_status_class(self):
		return self.get_status_info()['class']

	title = models.CharField(u'행사명',max_length=255)
	short_title = models.CharField(u'짧은 행사명',max_length=30)

	series = models.ForeignKey(u'Series', verbose_name=u'시리즈명', related_name=u'event')
	company = models.ForeignKey(EventCompany, verbose_name=u'이벤트사', related_name=u'event')

	desc = models.TextField(u'세부설명', blank=True)
	requested = models.IntegerField(u'요청 인원(명)', blank=True, default=20)

	location = models.CharField(u'장소', max_length=255)
	location_url = models.CharField(u'장소링크', max_length=255)

	support = models.IntegerField(u'지원금액', default=15000)

	course = ModelListField(Course,'title')
	participants = models.TextField(u'참가자 설명', blank=True)

	event_day = models.DateField(u'대회일', blank=True)
	assemble_time = models.TimeField(u'집결 시간', blank=True)
	race_time = models.TimeField(u'출발 시간', blank=True)

	recruit_open = models.DateField(u'등록 시작일', blank=True, null=True)
	recruit_deadline = models.DateField(u'등록 마감일', blank=True, null=True)
	feedback_deadline = models.DateField(u'후기 작성 종료일', blank=True, null=True)




class EventImage(models.Model):
	class Meta:
		verbose_name = u"행사 사진"
		verbose_name_plural = u"행사 사진들"
		ordering = ['event','order']

	def __unicode__(self):
		return self.title

	title = models.CharField(u'이미지설명', max_length=255, blank=True)
	image = models.FileField(upload_to=u'event/images/', verbose_name=u'이미지')
	featured = models.BooleanField(verbose_name=u'표지 사진 여부')
	event = models.ForeignKey(Event, verbose_name=u'행사', related_name='images')
	order = models.IntegerField('순서', default=0)

ENTRY_TYPE_CHOICES = (
		(u'wk',u'도보 패트롤'),
		(u'il',u'인라인 패트롤'),
		(u'cp',u'본부/현장스탭'),
	)

DISTANCE_TYPE_CHOICES = (
		(u'0',u'본부'),
		(u'5',u'0~5Km'),
		(u'10',u'5~10Km'),
		(u'20',u'10~20Km'),
		(u'30',u'20~30Km'),
		(u'30+',u'30Km 이상'),
	)

TSIZE_CHOICES = (
		(u'85',u'85(XS)'),
		(u'90',u'90(S)'),
		(u'95',u'95(M)'),
		(u'100',u'100(L)'),
		(u'105',u'105(XL)'),
		(u'110',u'110(XXL)'),
	)

CARPOOL_TYPE_CHOICES = (
		(u'none', u'카풀 안함(기본)'),
		(u'serv', u'카풀 제공 가능'),
		(u'need', u'카풀 받기를 원함'),
	)

class Skill(models.Model):
    class Meta:
        verbose_name = _('# Skill')
        verbose_name_plural = _('# Skills')

    def __unicode__(self):
        return self.name

    name = models.CharField(u'스킬명', max_length=32)
    desc = models.TextField(u'부가설명', blank=True)


class Entry(models.Model):

	class Meta:
		verbose_name = u"패트롤 신청"
		verbose_name_plural = u"패트롤 신청 목록"

	def __unicode__(self):
		return self.name

	def save(self):

		try:
			group = ContactGroup.objects.get(name=u'최종(자동업데이트)')

			try:
				group.items.get(cell=self.cell)

			except ObjectDoesNotExist:
				nitem = ContactItem()
				nitem.group = group
				nitem.name = self.name
				nitem.cell = self.cell
				nitem.etc1 = u'자동추가 @%s' % self.event.title
				nitem.save()

		except ObjectDoesNotExist:
			logger.error('Auto Update ContactGroup Not Found')
		except:
			logger.error('Unknown Exception')
			pass

		super(Entry,self).save()


	def digest(self):
		digest = {
			'display':"%s (%sXXXX)"%(self.name,self.cell[:-4]),
			'name':self.name,
			'entry':self.pk
		}
		return digest

	def short_etc(self):
		return truncatechars(self.etc, 20)

	def carpool_digest(self):
		digest = {
			'display': "%s (%s)"%(self.name,self.location),
			'entry': self.pk
		}
		return digest

	def skill_display(self):
		skill = [ sk.name for sk in Skill.objects.filter(pk__in=self.skill)]
		return ", ".join(skill)

	skill_display.short_description = u"가능 기술"

	event = models.ForeignKey(Event, verbose_name=u'행사')
	user = models.ForeignKey(User, verbose_name=u'대원', null=True, blank=True)

	club = models.CharField(u'소속 동호회', max_length=128)

	name = models.CharField(u'이름', max_length=32)
	cell = models.CharField(u'휴대폰', max_length=32)
	regnum = models.CharField(u'주민번호', max_length=15)

	htype = models.CharField(u'희망타입', max_length=2, choices=ENTRY_TYPE_CHOICES, blank=True)
	hdist = models.CharField(u'희망거리', max_length=5, choices=DISTANCE_TYPE_CHOICES, blank=True)

	carpool = models.CharField(u'카풀여부', max_length=4, choices=CARPOOL_TYPE_CHOICES, blank=True)
	location = models.CharField(u'지역', max_length=32, blank=True)

	tsize = models.CharField(u'티셔츠사이즈', max_length=5, choices=TSIZE_CHOICES)
	mileage = models.CharField(u'마일리지', max_length=32, blank=True)

	skill = ModelListField(Skill,'name')

	etc = models.TextField(u'요청사항', blank=True)


class Agent(models.Model):

	class Meta:
		verbose_name = u"대원"
		verbose_name_plural = u"대원 명단"

	def __unicode__(self):
		return "%s(%s)"%(self.user.first_name, self.user.username)

	def regnum_masked(self):
		return self.regnum[:6]+"-*******"

	def skill_display(self):
		skill = [ sk.name for sk in Skill.objects.filter(pk__in=self.skill)]
		return ", ".join(skill)

	def image_url(self):
		if self.image.name:
			return self.image.url+'=s280-c'

		return '/static/image/noface.png'

	user = models.OneToOneField(User, related_name='agent')

core/templates/core/carpool_sms_sent.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="page-header">
		<h3>문자 전송 내역 <small>{{ entry.event.title }}</small></h3>
	</div>

	<b>{{event.series.title}}</b>
	<dl class="dl-horizontal">
		<dt>장소:</dt> <dd>{{entry.event.location}}</dd>
		<dt>집합시간:</dt> <dd>{{entry.event.assemble_time}}</dd>
		<dt>출발시간:</dt> <dd>{{entry.event.race_time}}</dd>
	</dl>
	<HR>
	<div class=" clearfix">
		<dl class="col-sm-6 dl-horizontal">
			<dt>대원명</dt><dd>{{ entry.name }}</dd>
		</dl>
		<dl class="col-sm-6 dl-horizontal">
			<dt>카풀</dt><dd>{{ entry.get_carpool_display }}</dd>
			<dt>지역</dt><dd>{{ entry.location }}</dd>
		</dl>
	</div>
	<HR>

	<div class="form-group">
		<dl class="dl-horizontal">
			<dt>발신자<dt><dd>{{ sms.caller }}</dd>
			<dt>수신자<dt><dd>{{ sms.callee }}</dd>
		</dt>		
		<dl class="dl">
			<dt>내용</dt><dd><pre>{{ sms.msg }}</pre></dd>
		</dt>
	</div>

	<HR>
	<div class="col-sm-12">
		<a href="{% url 'event' entry.event.id %}" class='btn btn-success btn-block btn-lg'>
			확인
		</a>
	</div>
</div>

{% endblock %}

core/templates/core/club_search.html
{% extends "base_form.html" %}

{% block form %}
    

    <form class="form-signin form-wide" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">소속 동호회를 입력해주세요.</h2>
        <HR>

        <div class="form-group">
            <input name="club" id="club" class="form-control" value="{{ club|default_if_none:'' }}" placeholder="동호회명">
        </div>
        <div class="form-group text-danger" id="help-text">
        </div>

        <div class="form-group">
        <button class="btn btn-large btn-primary" type="submit">
            계속 <i class="fa fa-caret-right"></i>
        </button>
        </div>
    </form>

<!-- /container -->

{% endblock %}

{% block script %}

<script>
    function updateInfo(){
        var club = $('#club').val()

        if ( club.toLowerCase() === 'kisp' ) {
            $('#help-text').text('* KISP 대원은 경우 가급적 "가입 신청" 후 로그인해서 신청해 주시기 바랍니다.');
        } else {
            $('#help-text').text('* 외부 동호회 회원 자격으로 신청 하시는 경우 식대의 잔액은 바로 지급 되는 대신, KISP 회원의 혜택을 모두 포기하게 됩니다.');
        }
    }

    $(function() {
        updateInfo();
        $('#club').on('keyup change',function() {
            updateInfo();
        })

    });

</script>

{% endblock %}

core/templates/core/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="page-header">
		<h3>Contact US <small>KISP 스탭들과 연락처 입니다</small></h3>
	</div>

	<h4>NAVER CAFE</h4>
	<div class="container">
		<a href="http://cafe.naver.com/kisp/" class="btn btn-info" target="_new">KISP 카페 바로가기 <span class="glyphicon glyphicon-new-window"></span></a><br><br>
		<small>* KISP는 네이버 카페를 중심으로 활동하고 있습니다.</small>
	</div>
	<BR>
	<h4>스탭진</h4>
	<div class="col-sm-3 text-center">
		<img src="/static/image/face_test.png" class="img-circle" width="140">
		<div class="text-center" style="margin-top:25px">
			<string>이원우</string> / 대장
		</div>
		<br>
		<div class="text-muted text-center">
			패트롤 요청, 협업 요청 담당<br>
			<a href="mailto:bluedisk@gmail.com"><span class="glyphicon glyphicon-envelope"></span> bluedisk@gmail.com</a>
		</div>
	</div>

	<div class="col-sm-3 text-center">
		<img src="/static/image/noface.png" class="img-circle" width="140">
		<div class="text-center" style="margin-top:25px">
			<string>김은희</string> / 회계
		</div>
		<br>
		<div class="text-muted text-center">
			회계, 운영 담당<br>
		</div>
	</div>

	<div class="col-sm-3 text-center">
		<img src="/static/image/noface.png" class="img-circle" width="140">
		<div class="text-center" style="margin-top:25px">
			<string>권혁진</string> / 부메니저
		</div>
		<br>
		<div class="text-muted text-center">
			패트롤 진행 담당<br>
		</div>
	</div>
	
	<div class="col-sm-3 text-center">
		<img src="/static/image/noface.png" class="img-circle" width="140">
		<div class="text-center" style="margin-top:25px">
			<string>김삼수</string> / 스탭
		</div>
		<br>
		<div class="text-muted text-center">
			패트롤 진행 담당<br>
		</div>
	</div>
	
</div>
<BR><BR>
<div class="container">
	<h4>대원들</h4>
	<div class="member-container">

		{% for member in members %}
		<div class="member-frame" style="background-image: url({{ member.image }}); ">
			<div class="member-name">{{member.name}}</div>
		</div>
		{% endfor %}


	</div>
</div>
{% endblock %}	

{% block head_extra %}
<style>
	.member-container {
		position:relative;
		left:50%;
		margin:0px;
		margin-left:-350px;
		width:700px;
		padding:0px;		
		cursor:pointer;
	}
	.member-frame {		
		position:relative;
		width:140px;
		height:140px;
		padding:0px;
		margin:0px;
		overflow:hidden;
		float:left;	

		background-color: #D0D0D0;
		background-repeat: no-repeat; 
		background-size: cover;
		background-position: center
	}
	.member-name {
		position: absolute;
		top:0px;
		left:0px;
		width:140px;
		height:140px;
		background-color: black;
		text-align: center;
		line-height: 140px;
		color:white;
		font-weight: bold;
		opacity: 0;
	}
</style>
{% endblock %}

{% block script %}
<script>

	$('.member-frame').on('mouseover',function() {
		$(this).find('div').animate({'opacity':'0.7'})
	});

	$('.member-frame').on('mouseout',function() {
		$(this).find('div').animate({'opacity':'0'})
	});

</script>
{% endblock %}

core/templates/core/entry_view.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="page-header">
		<h3>신청 내역 <small>{{ entry.event.title }}</small></h3>
	</div>

	<b>{{event.series.title}}</b>
	<dl class="dl-horizontal">
		<dt>장소:</dt> <dd>{{entry.event.location}}</dd>
		<dt>집합시간:</dt> <dd>{{entry.event.assemble_time}}</dd>
		<dt>출발시간:</dt> <dd>{{entry.event.race_time}}</dd>
	</dl>
	<HR>
	<div class=" clearfix">
		<dl class="col-sm-6 dl-horizontal">
			<dt>대원명</dt><dd>{{ entry.name }}</dd>
			{% if me %}
			<dt>휴대폰</dt><dd>{{ entry.cell }}</dd>
			<dt>주민번호</dt><dd>{{ entry.regnum }}</dd>
			{% endif %}
		</dl>
		<dl class="col-sm-6 dl-horizontal">
			<dt>패트롤 타입</dt><dd>{{ entry.get_htype_display }}</dd>
			
			{% if me %}
			<dt>패트롤 거리</dt><dd>{{ entry.get_hdist_display }}</dd>
			<dt>티셔츠 사이즈</dt><dd>{{ entry.tsize }}</dd>
			<dt>마일리지</dt><dd>{{ entry.milesage }}</dd>
			{% endif %}
		</dl>
		<dl class="col-sm-6 dl-horizontal">
			<dt>카풀</dt><dd>{{ entry.get_carpool_display }}</dd>
			<dt>지역</dt><dd>{{ entry.location }}</dd>
		</dl>
		<dl class="col-sm-6 dl-horizontal">
			{% if me %}
			<dt>가능스킬</dt><dd>{{ entry.skill_display }}</dd>
			{% endif %}
		</dl>
{% if me %}
		<dl class="col-sm-10 col-sm-offset-1">
			<dt>그 외 요청사항</dt><dd class='well'>{{ entry.etc }}</dd>
		</dl>
{% endif %}

	</div>
	<HR>
{% if not me %}
	<form rule="form" method="post">
	{% csrf_token %}
	<div class="container">
		<h3>문자 보내기</h3>

		<div class="col-sm-7">
			<div class="form-group{% if form.caller.errors %} has-error{% endif %}">
				<label for="caller">보낸 사람 번호</label>
				<input type="text" class="form-control" name="caller" id="caller" placeholder="반드시 본인 휴대폰 번호를 입력해주세요." value="{% firstof user.agent.cell form.caller.value '' %}">
				<span class="help-block">{{ form.caller.errors }}</span>
			</div>
			<div class="form-group{% if form.msg.errors %} has-error{% endif %}">
				<label for="msg">보낼 메시지</label>
				<input type="text" class="form-control" name="msg" id="msg" maxlength='80' placeholder="80Byte 이내로 입력해주세요. 전송한 모든 내용은 저장됩니다." value="{{ form.msg.value|default_if_none:'' }}">
				<span class="help-block">{{ form.msg.errors }}</span>
			</div>
		</div>
		<div class="col-sm-5">
			<div class="form-group{% if form.captcha.errors %} has-error{% endif %}">
			<label for="captcha">자동 입력 방지</label>
			{{ form.captcha }}				
			<span class="help-block">{{ form.captcha.errors }}</span>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="col-sm-7">
			<button class="btn btn-danger" type="submit">문자 전송</button>
		</div>
	</div>
	</form>
	<HR>
{% endif %}
<div class='container'>
{% if my_entry_id == entry.id %}
	<div class="col-sm-8">
		<a href="{% url 'event' entry.event.id %}" class='btn btn-info btn-block btn-lg'>
			"{{entry.event.title}}" 행사로 돌아가기
		</a>
	</div>
	<div class="col-sm-4">
		{% if user.is_authenticated %}
		<a href="{% url 'agent_entry_edit' entry.event.id %}" class='btn btn-warning btn-block btn-lg'>
		{% else %}
		<a href="{% url 'entry_edit' entry.id %}" class='btn btn-warning btn-block btn-lg'>
		{% endif %}
			신청 내용 수정
		</a>
	</div>
{% else %}
	<div class="col-sm-12">
		<a href="{% url 'event' entry.event.id %}" class='btn btn-info btn-block btn-lg'>
			"{{entry.event.title}}" 행사로 돌아가기
		</a>
	</div>
{% endif %}
</div>

{% endblock %}